### ISSUE TITLE
grunt: TypeError: grunt.data.json.years is not iterable

### ISSUE THREAD

**Issue by raineorshine** [nprapps/book-concierge#75]
How do I set `grunt.data.json.years`? It is `undefined` for me.

Thanks!

```
$ grunt
Running "clean" task

Running "copy" task

Running "bundle" task
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

Running "less" task

Running "state" task

Running "json" task

Running "csv" task

Running "markdown" task

Running "archieml" task

Running "shelve" task
(node:31223) UnhandledPromiseRejectionWarning: TypeError: grunt.data.json.years is not iterable
  at shelve (/Users/raine/projects/book-concierge/tasks/shelve.js:19:35)
  at Object.<anonymous> (/Users/raine/projects/book-concierge/tasks/shelve.js:92:5)
  at Object.thisTask.fn (/Users/raine/projects/book-concierge/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Users/raine/projects/book-concierge/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/raine/projects/book-concierge/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/raine/projects/book-concierge/node_modules/grunt/lib/util/task.js:293:12)
  at /Users/raine/projects/book-concierge/node_modules/grunt/lib/util/task.js:220:11
  at processTicksAndRejections (internal/process/task_queues.js:75:11)

(node:31223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by thomaswilburn** [comment]
This should be in the README, but all properties on grunt.data.json come from Sheets.

**Comment by raineorshine** [comment]
Is there a template for the sheet somewhere? I tried adding a Years column but that didn't seem to work.

**Comment by thomaswilburn** [comment]
There's not, unfortunately, a template for the sheets themselves (cleaning it up is kind of a bear), but one thing to watch out for is that column names are case sensitive, and to be sure to pull the sheet down after any remote change.

**Comment by raineorshine** [comment]
Ah, I see, it requires a separate sheet called "years"!

Can you provide a list of the required sheets and their columns? I'd like to avoid having to reverse engineer each one. Thanks!

**Comment by thomaswilburn** [comment]
Yes, those are all in the readme.

**Comment by raineorshine** [comment]
Ah, thanks!
